"""Initial migration

Revision ID: ef33e86f64db
Revises: 
Create Date: 2025-11-21 03:33:52.497463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef33e86f64db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legislations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('simplified_content', sa.Text(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('impact_analysis', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislations_external_id'), 'legislations', ['external_id'], unique=True)
    op.create_index(op.f('ix_legislations_status'), 'legislations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legislations_status'), table_name='legislations')
    op.drop_index(op.f('ix_legislations_external_id'), table_name='legislations')
    op.drop_table('legislations')
    # ### end Alembic commands ###

